version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    volumes:
      # Mount source code for hot reloading
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - edullm-network
    # Allow access to host machine (for backend connection)
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  edullm-network:
    driver: bridge
